version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./server
    ports:
      - "4000:5000"
      - "5005:5005"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - START_RAG=true
      # Si te conectas a Ollama localmente, usa esta variable:
      - OLLAMA_HOST=host.docker.internal
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: danhee_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# Volumen definido para la persistencia de datos
volumes:
  db_data: